language: cpp
sudo: required
dist: focal
compiler: gcc
os:
- linux



install:
  - wget http://ftp.gnu.org/gnu/guile/guile-1.8.8.tar.gz
  - tar -xzvf guile-1.8.8.tar.gz
  - pushd guile-1.8.8 && ./configure --prefix=/usr  --disable-error-on-warning && make && sudo make install && popd

addons:
  apt:
    packages:
      - libssl-dev
      - g++
      - qtbase5-dev
      - libqt5svg5-dev
      - libfreetype-dev
      - libsqlite-dev
      - libjpeg-dev
      - cmake
      - cmake-data

script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build .
