language: cpp
sudo: required
#dist: focal
compiler: gcc
#os:
#- linux
#- osx

jobs:
  include:
    - 
      os: linux
      dist: focal
    - 
      os: osx
      osx_image: xcode13.1

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl -o guile@1.8.rb https://raw.githubusercontent.com/texmacs/homebrew/master/guile%401.8.rb; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew unlink guile; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install guile@1.8.rb; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install freetype libjpeg qt@5; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://ftp.gnu.org/gnu/guile/guile-1.8.8.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then tar -xzvf guile-1.8.8.tar.gz ;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pushd guile-1.8.8 && ./configure --prefix=/usr  --disable-error-on-warning && make && sudo make install && popd; fi

addons:
  apt:
    packages:
      - libssl-dev
      - g++
      - qtbase5-dev
      - libqt5svg5-dev
      - libfreetype-dev
      - libsqlite-dev
      - libjpeg-dev
      - cmake
      - cmake-data

script:
  - mkdir build && cd build
  - cmake .. -DTEXMACS_GUI=Qt5
  - cmake  --build .
