language: cpp
sudo: required
dist: focal
compiler: gcc
os:
- linux



install:
#  - wget https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2.tar.gz
#  - tar -zxvf cmake-3.20.2.tar.gz
#  - pushd cmake-3.20.2 && ./bootstrap && make && sudo make install 
  - wget http://ftp.gnu.org/gnu/guile/guile-1.8.8.tar.gz
  - tar -xzvf guile-1.8.8.tar.gz
  - pushd guile-1.8.8 && ./configure --prefix=/usr  --disable-error-on-warning && make && sudo make install && popd
#  - sudo snap install cmake --classic

addons:
  apt:
    packages:
      - libssl-dev
      - g++
      - qtbase5-dev
      - cmake
      - cmake-data

script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build .
